# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fullscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import screen_width, screen_height
from DisplayLabel import DisplayLabel


class Ui_Splitscreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(192, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, screen_width, screen_height))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.line = 0

        self.display_label_1 = DisplayLabel(self.centralwidget, 1)
        self.display_label_1.setObjectName("display_label_1")
        self.display_label_1.setStyleSheet("background-image: url(./fullscreen.png)")
        self.display_label_1.setGeometry(QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

        self.line = 1

        self.display_label_2 = DisplayLabel(self.centralwidget, 2)
        self.display_label_2.setObjectName("display_label_2")
        self.display_label_2.setStyleSheet("background-image: url(./fullscreen.png)")
        self.display_label_2.setGeometry(QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

        self.line = 2

        self.display_label_3 = DisplayLabel(self.centralwidget, 3)
        self.display_label_3.setObjectName("display_label_3")
        self.display_label_3.setStyleSheet("background-image: url(./fullscreen.png)")
        self.display_label_3.setGeometry(QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

