# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fullscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtWidgets import QVBoxLayout

from DisplayLabel import DisplayLabel
from data import screen_width, screen_height, ip_fs
from utils.req import req


class Ui_Splitscreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(192, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        layout = QVBoxLayout()

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, screen_width, screen_height))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(layout)

        try:
            self.fetched_datas = req("get", ip_fs).json()
        except:
            print("cant fetch datas")

        self.line = 0

        if self.fetched_datas[1]['format'] == 'mp4':

            videoWidget_1 = QVideoWidget()
            wid = QtWidgets.QWidget(MainWindow)
            self.mediaPlayer_1 = QMediaPlayer(None, QMediaPlayer.VideoSurface)
            layout = QVBoxLayout()
            layout.addWidget(videoWidget_1)
            wid.setLayout(layout)
            videoWidget_1.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))
            self.mediaPlayer_1.setObjectName("display_label")
            self.mediaPlayer_1.setVideoOutput(videoWidget_1)
            self.mediaPlayer_1.setMedia(QMediaContent(QUrl.fromLocalFile('/home/pi/jde/panel/GUI/Chats.mp4')))
            self.mediaPlayer_1.play()
        else:
            self.display_label_1 = DisplayLabel(self.centralwidget, 1)
            self.display_label_1.setObjectName("display_label_1")
            self.display_label_1.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

        self.line = 1

        if self.fetched_datas[2]['format'] == 'mp4':
            videoWidget_2 = QVideoWidget()
            wid = QtWidgets.QWidget(MainWindow)
            MainWindow.setCentralWidget(wid)
            self.mediaPlayer_2 = QMediaPlayer(None, QMediaPlayer.VideoSurface)
            layout = QVBoxLayout()
            layout.addWidget(videoWidget_2)
            wid.setLayout(layout)
            videoWidget_2.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))
            self.mediaPlayer_2.setObjectName("display_label")
            self.mediaPlayer_2.setVideoOutput(videoWidget_2)
            self.mediaPlayer_2.setMedia(QMediaContent(QUrl.fromLocalFile('/home/pi/jde/panel/GUI/Chats.mp4')))
            self.mediaPlayer_2.play()
        else:
            self.display_label_2 = DisplayLabel(self.centralwidget, 2)
            self.display_label_2.setObjectName("display_label_2")
            self.display_label_2.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

            self.line = 2

        if self.fetched_datas[3]['format'] == 'mp4':
            videoWidget_3 = QVideoWidget()
            wid = QtWidgets.QWidget(MainWindow)
            MainWindow.setCentralWidget(wid)
            self.mediaPlayer_3 = QMediaPlayer(None, QMediaPlayer.VideoSurface)
            layout = QVBoxLayout()
            layout.addWidget(videoWidget_3)
            wid.setLayout(layout)
            videoWidget_3.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))
            self.mediaPlayer_3.setObjectName("display_label")
            self.mediaPlayer_3.setVideoOutput(videoWidget_3)
            self.mediaPlayer_3.setMedia(QMediaContent(QUrl.fromLocalFile('/home/pi/jde/panel/GUI/Chats.mp4')))
            self.mediaPlayer_3.play()
        else:
            self.display_label_3 = DisplayLabel(self.centralwidget, 3)
            self.display_label_3.setObjectName("display_label_3")
            self.display_label_3.setGeometry(
                QtCore.QRect(0, 0 + (screen_height / 3 * self.line), screen_width, screen_height / 3))

        layout.addWidget(videoWidget_1) if videoWidget_1 else layout.addWidget(self.display_label_1)
        layout.addWidget(videoWidget_2) if videoWidget_2 else layout.addWidget(self.display_label_2)
        layout.addWidget(videoWidget_3) if videoWidget_3 else layout.addWidget(self.display_label_3)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
